export const CART_ITEM_REQUEST = "CART_ITEM_REQUEST";
export const CART_ITEM_ADD = "CART_ITEM_ADD";
export const CART_ITEM_FAIL = "CART_ITEM_FAIL";
export const CART_ITEM_REMOVE = "CART_ITEM_REMOVE";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_EMPTY = "CART_EMPTY";
